"""sync_schema_with_models

Revision ID: 1b230a4931d9
Revises: 
Create Date: 2026-05-24 23:11:25.611883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b230a4931d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('assembly_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('motions', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('party', sa.String(), nullable=True))
    op.add_column('users', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_users_group_id_groups',
        'users',
        'groups',
        ['group_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_group_id_groups', 'users', type_='foreignkey')
    op.drop_column('users', 'group_id')
    op.drop_column('users', 'party')
    op.drop_column('motions', 'closed_at')
    op.drop_table('groups')
    # ### end Alembic commands ###
